Vulcan 650/expanded cell renderer
mercedes-benz/neodash pull request #114
Opened 2024-04-23 10:22 UTC by anayabhat

2024-04-29 04:25 UTC, brahmprakashMishra requested changes

2024-05-02 11:23 UTC, anayabhat commented on src/component/misc/DataGridExpandRenderer.tsx
> +import { RenderString } from '../../report/ReportRecordProcessing';
Source code has relative import used every where.

2024-05-02 11:24 UTC, anayabhat commented on src/component/misc/DataGridExpandRenderer.tsx
> +  if (typeof value === 'string' || value instanceof String) {
RenderString(value) is a re-used function.

2024-05-06 06:42 UTC, brahmprakashMishra approved these changes

2024-05-06 06:42 UTC, merged